server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Shu@2022
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.url=jdbc:mysql://localhost:3306/edb
#  spring.datasource.username=newuser
#  spring.datasource.password=password123
#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
